/* ══════════════════════════════════════════════════════════════
   MagiCounter — データ層（タイプ・相性表・ポケモン・技・特性・持ち物・編成）
   ──────────────────────────────────────────────────────────────
   ★ このファイルは<b>数字と名前だけ</b>を持ちます。計算は mc-core.js、
     画面は mc-ui.js。3つを分けているので、環境データの入れかえだけで
     アプリ全体が新しい環境に追従できます。

   ★★ 使用率・勝率・トレンドについて（大切）
     Pokémon Champions の<b>公式の統計は公開されていません</b>。
     ここに入っている usage / win / trend は
     <b>この土台に入れてある初期値（サンプル）</b>です。
     オンラインに戻ると mc-core.js の MC.meta.refresh() が
     <b>data/meta.json</b>（同じフォルダ）を読みに行き、
     新しい数字があればそれで上書きして端末に保存します。
     ＝ 数字を差しかえるときは<b>このファイルではなく meta.json</b>を置きかえる。

   ★ 相性表・種族値・タイプは<b>ゲームの規則そのもの</b>なので、
     こちらが持ち主です（meta.json では上書きしません）。
   ══════════════════════════════════════════════════════════════ */
(function () {
  "use strict";

  /* ══════════ ① タイプ（18） ══════════ */
  const TYPES = [
    { k: "normal",   ja: "ノーマル",   en: "Normal",   c: "#9fa19f" },
    { k: "fire",     ja: "ほのお",     en: "Fire",     c: "#e8622b" },
    { k: "water",    ja: "みず",       en: "Water",    c: "#2f86d8" },
    { k: "electric", ja: "でんき",     en: "Electric", c: "#e8c000" },
    { k: "grass",    ja: "くさ",       en: "Grass",    c: "#3fa129" },
    { k: "ice",      ja: "こおり",     en: "Ice",      c: "#3fd8ff" },
    { k: "fighting", ja: "かくとう",   en: "Fighting", c: "#c03028" },
    { k: "poison",   ja: "どく",       en: "Poison",   c: "#9141cb" },
    { k: "ground",   ja: "じめん",     en: "Ground",   c: "#b0813f" },
    { k: "flying",   ja: "ひこう",     en: "Flying",   c: "#81b9ef" },
    { k: "psychic",  ja: "エスパー",   en: "Psychic",  c: "#ef4179" },
    { k: "bug",      ja: "むし",       en: "Bug",      c: "#91a119" },
    { k: "rock",     ja: "いわ",       en: "Rock",     c: "#afa981" },
    { k: "ghost",    ja: "ゴースト",   en: "Ghost",    c: "#704170" },
    { k: "dragon",   ja: "ドラゴン",   en: "Dragon",   c: "#5060e1" },
    { k: "dark",     ja: "あく",       en: "Dark",     c: "#50413f" },
    { k: "steel",    ja: "はがね",     en: "Steel",    c: "#60a1b8" },
    { k: "fairy",    ja: "フェアリー", en: "Fairy",    c: "#ef70ef" },
  ];
  const TK = TYPES.map((t) => t.k);

  /* ══════════ ② 相性表 ══════════
     CHART[攻撃タイプ][防御タイプ] = 倍率（0 / 0.5 / 1 / 2）
     ★ 書いていない組み合わせは 1 倍。データ量を抑えるため
       <b>2倍・0.5倍・0倍だけ</b>を並べてある。 */
  const X2 = {
    normal:   { rock: .5, ghost: 0, steel: .5 },
    fire:     { fire: .5, water: .5, grass: 2, ice: 2, bug: 2, rock: .5, dragon: .5, steel: 2 },
    water:    { fire: 2, water: .5, grass: .5, ground: 2, rock: 2, dragon: .5 },
    electric: { water: 2, electric: .5, grass: .5, ground: 0, flying: 2, dragon: .5 },
    grass:    { fire: .5, water: 2, grass: .5, poison: .5, ground: 2, flying: .5, bug: .5, rock: 2, dragon: .5, steel: .5 },
    ice:      { fire: .5, water: .5, grass: 2, ice: .5, ground: 2, flying: 2, dragon: 2, steel: .5 },
    fighting: { normal: 2, ice: 2, poison: .5, flying: .5, psychic: .5, bug: .5, rock: 2, ghost: 0, dark: 2, steel: 2, fairy: .5 },
    poison:   { grass: 2, poison: .5, ground: .5, rock: .5, ghost: .5, steel: 0, fairy: 2 },
    ground:   { fire: 2, electric: 2, grass: .5, poison: 2, flying: 0, bug: .5, rock: 2, steel: 2 },
    flying:   { electric: .5, grass: 2, fighting: 2, bug: 2, rock: .5, steel: .5 },
    psychic:  { fighting: 2, poison: 2, psychic: .5, dark: 0, steel: .5 },
    bug:      { fire: .5, grass: 2, fighting: .5, poison: .5, flying: .5, psychic: 2, ghost: .5, dark: 2, steel: .5, fairy: .5 },
    rock:     { fire: 2, ice: 2, fighting: .5, ground: .5, flying: 2, bug: 2, steel: .5 },
    ghost:    { normal: 0, psychic: 2, ghost: 2, dark: .5 },
    dragon:   { dragon: 2, steel: .5, fairy: 0 },
    dark:     { fighting: .5, psychic: 2, ghost: 2, dark: .5, fairy: .5 },
    steel:    { fire: .5, water: .5, electric: .5, ice: 2, rock: 2, steel: .5, fairy: 2 },
    fairy:    { fire: .5, fighting: 2, poison: .5, dragon: 2, dark: 2, steel: .5 },
  };
  /* 完全な 18×18 に展開しておく（毎回 undefined を見にいかないため） */
  const CHART = {};
  TK.forEach((a) => {
    CHART[a] = {};
    TK.forEach((d) => { CHART[a][d] = (X2[a] && X2[a][d] != null) ? X2[a][d] : 1; });
  });

  /* ══════════ ③ 役割（ロール） ══════════ */
  const ROLES = [
    { k: "sweeper",  ja: "アタッカー",   en: "Sweeper" },
    { k: "wall",     ja: "耐久・受け",   en: "Wall" },
    { k: "support",  ja: "サポート",     en: "Support" },
    { k: "speed",    ja: "高速",         en: "Fast" },
    { k: "setup",    ja: "積み",         en: "Setup" },
    { k: "pivot",    ja: "起点作り",     en: "Pivot" },
    { k: "trick",    ja: "妨害",         en: "Disruptor" },
    { k: "tank",     ja: "耐久アタッカー", en: "Bulky Attacker" },
  ];

  /* ══════════ ④ 特性 ══════════
     eff … 相性計算に効くもの（mc-core.js が読む）
       immune:<type>   … そのタイプを無効化する
       half:<type>     … そのタイプを半減する
       weakhalf        … こうかばつぐんを半減（ハードロック等）
     それ以外は説明だけ。 */
  const ABIL = {
    intimidate:   { ja: "いかく",         en: "Intimidate",   d: { ja: "出たとき相手の攻撃を1段階下げる", en: "Lowers foe's Attack on entry" } },
    levitate:     { ja: "ふゆう",         en: "Levitate",     eff: "immune:ground", d: { ja: "じめん技を受けない", en: "Immune to Ground" } },
    flashfire:    { ja: "もらいび",       en: "Flash Fire",   eff: "immune:fire", d: { ja: "ほのお技を無効化し、自分のほのお技が強くなる", en: "Immune to Fire; powers up Fire" } },
    waterabsorb:  { ja: "ちょすい",       en: "Water Absorb", eff: "immune:water", d: { ja: "みず技を受けるとHPが回復する", en: "Heals from Water" } },
    voltabsorb:   { ja: "ちくでん",       en: "Volt Absorb",  eff: "immune:electric", d: { ja: "でんき技を受けるとHPが回復する", en: "Heals from Electric" } },
    lightningrod: { ja: "ひらいしん",     en: "Lightning Rod", eff: "immune:electric", d: { ja: "でんき技を引き寄せて無効化し、特攻が上がる", en: "Draws in Electric; raises Sp.Atk" } },
    stormdrain:   { ja: "よびみず",       en: "Storm Drain",  eff: "immune:water", d: { ja: "みず技を引き寄せて無効化し、特攻が上がる", en: "Draws in Water; raises Sp.Atk" } },
    sapsipper:    { ja: "そうしょく",     en: "Sap Sipper",   eff: "immune:grass", d: { ja: "くさ技を無効化し、攻撃が上がる", en: "Immune to Grass; raises Attack" } },
    thickfat:     { ja: "あついしぼう",   en: "Thick Fat",    eff: "half:fire,ice", d: { ja: "ほのお・こおり技のダメージを半分にする", en: "Halves Fire and Ice damage" } },
    heatproof:    { ja: "たいねつ",       en: "Heatproof",    eff: "half:fire", d: { ja: "ほのお技のダメージを半分にする", en: "Halves Fire damage" } },
    waterbubble:  { ja: "すいほう",       en: "Water Bubble", eff: "half:fire", d: { ja: "ほのお技を半減し、自分のみず技が2倍", en: "Halves Fire; doubles own Water" } },
    solidrock:    { ja: "ハードロック",   en: "Solid Rock",   eff: "weakhalf", d: { ja: "こうかばつぐんのダメージを軽くする", en: "Reduces super-effective damage" } },
    filter:       { ja: "フィルター",     en: "Filter",       eff: "weakhalf", d: { ja: "こうかばつぐんのダメージを軽くする", en: "Reduces super-effective damage" } },
    prismarmor:   { ja: "プリズムアーマー", en: "Prism Armor", eff: "weakhalf", d: { ja: "こうかばつぐんのダメージを軽くする", en: "Reduces super-effective damage" } },
    multiscale:   { ja: "マルチスケイル", en: "Multiscale",   d: { ja: "HP満タンのとき受けるダメージが半分", en: "Halves damage at full HP" } },
    disguise:     { ja: "ばけのかわ",     en: "Disguise",     d: { ja: "1回だけ攻撃を防ぐ", en: "Blocks one hit" } },
    protean:      { ja: "へんげんじざい", en: "Protean",      d: { ja: "出す技のタイプに自分が変わる", en: "Becomes the type of its move" } },
    libero:       { ja: "リベロ",         en: "Libero",       d: { ja: "出す技のタイプに自分が変わる", en: "Becomes the type of its move" } },
    hugepower:    { ja: "ちからもち",     en: "Huge Power",   d: { ja: "攻撃が2倍になる", en: "Doubles Attack" } },
    guts:         { ja: "こんじょう",     en: "Guts",         d: { ja: "状態異常のとき攻撃が上がる", en: "Boosts Attack when statused" } },
    speedboost:   { ja: "かそく",         en: "Speed Boost",  d: { ja: "毎ターン素早さが上がる", en: "Raises Speed each turn" } },
    drought:      { ja: "ひでり",         en: "Drought",      d: { ja: "出たとき晴れにする", en: "Summons harsh sunlight" } },
    drizzle:      { ja: "あめふらし",     en: "Drizzle",      d: { ja: "出たとき雨にする", en: "Summons rain" } },
    sandstream:   { ja: "すなおこし",     en: "Sand Stream",  d: { ja: "出たとき砂嵐にする", en: "Summons a sandstorm" } },
    snowwarning:  { ja: "ゆきふらし",     en: "Snow Warning", d: { ja: "出たとき雪にする", en: "Summons snow" } },
    electricsurge:{ ja: "エレキメイカー", en: "Electric Surge", d: { ja: "エレキフィールドを張る", en: "Sets Electric Terrain" } },
    psychicsurge: { ja: "サイコメイカー", en: "Psychic Surge", d: { ja: "サイコフィールドを張る", en: "Sets Psychic Terrain" } },
    grassysurge:  { ja: "グラスメイカー", en: "Grassy Surge", d: { ja: "グラスフィールドを張る", en: "Sets Grassy Terrain" } },
    mistysurge:   { ja: "ミストメイカー", en: "Misty Surge",  d: { ja: "ミストフィールドを張る", en: "Sets Misty Terrain" } },
    regenerator:  { ja: "さいせいりょく", en: "Regenerator",  d: { ja: "引っこむとHPが回復する", en: "Heals on switch out" } },
    unaware:      { ja: "てんねん",       en: "Unaware",      d: { ja: "相手の能力変化を無視する", en: "Ignores stat changes" } },
    prankster:    { ja: "いたずらごころ", en: "Prankster",    d: { ja: "変化技が先に出る", en: "Status moves go first" } },
    beastboost:   { ja: "ビーストブースト", en: "Beast Boost", d: { ja: "倒すと一番高い能力が上がる", en: "Boosts best stat on KO" } },
    goodasgold:   { ja: "おうごんのからだ", en: "Good as Gold", d: { ja: "相手の変化技を受けない", en: "Immune to status moves" } },
    supremeoverlord: { ja: "そうだいしょう", en: "Supreme Overlord", d: { ja: "倒れた味方の数だけ強くなる", en: "Stronger per fallen ally" } },
    quarkdrive:   { ja: "クォークチャージ", en: "Quark Drive", d: { ja: "エレキフィールドで一番高い能力が上がる", en: "Boosts best stat in Electric Terrain" } },
    protosynthesis: { ja: "こだいかっせい", en: "Protosynthesis", d: { ja: "晴れで一番高い能力が上がる", en: "Boosts best stat in sun" } },
    sturdy:       { ja: "がんじょう",     en: "Sturdy",       d: { ja: "一撃では倒れない", en: "Survives a one-hit KO" } },
    magicguard:   { ja: "マジックガード", en: "Magic Guard",  d: { ja: "攻撃技以外でダメージを受けない", en: "Only damaged by attacks" } },
    naturalcure:  { ja: "しぜんかいふく", en: "Natural Cure", d: { ja: "引っこむと状態異常が治る", en: "Cures status on switch" } },
    swiftswim:    { ja: "すいすい",       en: "Swift Swim",   d: { ja: "雨のとき素早さが2倍", en: "Doubles Speed in rain" } },
    chlorophyll:  { ja: "ようりょくそ",   en: "Chlorophyll",  d: { ja: "晴れのとき素早さが2倍", en: "Doubles Speed in sun" } },
    swordofruin:  { ja: "わざわいのつるぎ", en: "Sword of Ruin", d: { ja: "まわりの防御を下げる", en: "Lowers others' Defense" } },
    beadsofruin:  { ja: "わざわいのたま", en: "Beads of Ruin", d: { ja: "まわりの特防を下げる", en: "Lowers others' Sp.Def" } },
    tabletsofruin:{ ja: "わざわいのおふだ", en: "Tablets of Ruin", d: { ja: "まわりの攻撃を下げる", en: "Lowers others' Attack" } },
    vesselofruin: { ja: "わざわいのうつわ", en: "Vessel of Ruin", d: { ja: "まわりの特攻を下げる", en: "Lowers others' Sp.Atk" } },
    zerotohero:   { ja: "ゼロのちから",   en: "Zero to Hero", d: { ja: "引っこむとヒーローフォルムになる", en: "Becomes Hero Form" } },
    ironfist:     { ja: "てつのこぶし",   en: "Iron Fist",    d: { ja: "パンチ技が強くなる", en: "Powers up punching moves" } },
    technician:   { ja: "テクニシャン",   en: "Technician",   d: { ja: "威力の低い技が強くなる", en: "Powers up weak moves" } },
    adaptability: { ja: "てきおうりょく", en: "Adaptability", d: { ja: "同じタイプの技がさらに強くなる", en: "Boosts same-type moves" } },
    hospitality:  { ja: "おもてなし",     en: "Hospitality",  d: { ja: "出たとき味方を回復する", en: "Heals ally on entry" } },
    purifyingsalt:{ ja: "きよめのしお",   en: "Purifying Salt", eff: "half:ghost", d: { ja: "状態異常にならず、ゴースト技を半減する", en: "Status immune; halves Ghost" } },
    fluffy:       { ja: "もふもふ",       en: "Fluffy",       d: { ja: "接触技を半減、ほのお技は2倍受ける", en: "Halves contact damage; weak to Fire" } },
    poisonheal:   { ja: "ポイズンヒール", en: "Poison Heal",  d: { ja: "毒のときHPが回復する", en: "Heals when poisoned" } },
    competitive:  { ja: "かちき",         en: "Competitive",  d: { ja: "能力を下げられると特攻が大きく上がる", en: "Sharply raises Sp.Atk when lowered" } },
    defiant:      { ja: "まけんき",       en: "Defiant",      d: { ja: "能力を下げられると攻撃が大きく上がる", en: "Sharply raises Attack when lowered" } },
    transistor:   { ja: "トランジスタ",   en: "Transistor",   d: { ja: "でんき技が強くなる", en: "Powers up Electric moves" } },
    dragonsmaw:   { ja: "りゅうのあぎと", en: "Dragon's Maw", d: { ja: "ドラゴン技が強くなる", en: "Powers up Dragon moves" } },
    hadronengine: { ja: "ハドロンエンジン", en: "Hadron Engine", d: { ja: "エレキフィールドを張り、特攻が上がる", en: "Sets Electric Terrain; boosts Sp.Atk" } },
    orichalcum:   { ja: "ひひいろのこどう", en: "Orichalcum Pulse", d: { ja: "晴れにして攻撃が上がる", en: "Summons sun; boosts Attack" } },
    asoneshadow:  { ja: "じんばいったい（黒）", en: "As One (Shadow)", d: { ja: "倒すと特攻が上がる／かげふみ", en: "Boosts Sp.Atk on KO; traps" } },
    asoneice:     { ja: "じんばいったい（白）", en: "As One (Ice)", d: { ja: "倒すと攻撃が上がる／きんちょうかん", en: "Boosts Attack on KO; Unnerve" } },
    intrepidsword:{ ja: "ふとうのけん",   en: "Intrepid Sword", d: { ja: "出たとき攻撃が上がる", en: "Raises Attack on entry" } },
    dauntlessshield: { ja: "ふくつのたて", en: "Dauntless Shield", d: { ja: "出たとき防御が上がる", en: "Raises Defense on entry" } },
    pressure:     { ja: "プレッシャー",   en: "Pressure",     d: { ja: "相手のPPを多く減らす", en: "Foe uses more PP" } },
    innerfocus:   { ja: "せいしんりょく", en: "Inner Focus",  d: { ja: "ひるまない・いかくを受けない", en: "Prevents flinching and Intimidate" } },
    static:       { ja: "せいでんき",     en: "Static",       d: { ja: "接触するとまひさせることがある", en: "May paralyze on contact" } },
    torrent:      { ja: "げきりゅう",     en: "Torrent",      d: { ja: "ピンチでみず技が強くなる", en: "Boosts Water when low HP" } },
    overgrow:     { ja: "しんりょく",     en: "Overgrow",     d: { ja: "ピンチでくさ技が強くなる", en: "Boosts Grass when low HP" } },
    blaze:        { ja: "もうか",         en: "Blaze",        d: { ja: "ピンチでほのお技が強くなる", en: "Boosts Fire when low HP" } },
    /* ── ポケモン側で使っているもののうち、上に並んでいなかった特性 ──
       ★ ここに無いと画面に<b>英字の id のまま</b>出てしまう。 */
    roughskin:    { ja: "さめはだ", en: "Rough Skin", d: { ja: "接触されると相手を削る", en: "Damages attackers on contact" } },
    sandveil:     { ja: "すなかきのべール", en: "Sand Veil", d: { ja: "砂嵐で回避率が上がる", en: "Raises evasion in a sandstorm" } },
    infiltrator:  { ja: "すりぬけ", en: "Infiltrator", d: { ja: "リフレクターやみがわりを無視する", en: "Ignores screens and Substitute" } },
    clearbody:    { ja: "クリアボディー", en: "Clear Body", d: { ja: "能力を下げられない", en: "Prevents stat drops" } },
    unseenfist:   { ja: "ミエネンのこぶし", en: "Unseen Fist", d: { ja: "まもるを貫いて当たる", en: "Contact moves bypass Protect" } },
    mirrorarmor:  { ja: "ミラーアーマー", en: "Mirror Armor", d: { ja: "能力下降をそのまま返す", en: "Reflects stat drops" } },
    ironbarbs:    { ja: "アイアンバーブ", en: "Iron Barbs", d: { ja: "接触されると相手を削る", en: "Damages attackers on contact" } },
    unnerve:      { ja: "きんちょうかん", en: "Unnerve", d: { ja: "相手のきのみを使わせない", en: "Foes cannot eat Berries" } },
    cursedbody:   { ja: "のろわれボディ", en: "Cursed Body", d: { ja: "受けた技をかなしばりにすることがある", en: "May disable a move used on it" } },
    traceability: { ja: "トレース", en: "Trace", d: { ja: "相手の特性をコピーする", en: "Copies the foe's Ability" } },
    synchronize:  { ja: "シンクロ", en: "Synchronize", d: { ja: "状態異常を相手にもうつす", en: "Passes status to the foe" } },
    justified:    { ja: "ジストフォース", en: "Justified", d: { ja: "あく技を受けると攻撃が上がる", en: "Raises Attack when hit by Dark" } },
    serenegrace:  { ja: "てんのめぐみ", en: "Serene Grace", d: { ja: "追加効果が出やすい", en: "Doubles secondary effect chance" } },
    superluck:    { ja: "ちょうラッキー", en: "Super Luck", d: { ja: "急所に当たりやすい", en: "Higher critical-hit ratio" } },
    oblivious:    { ja: "どんかん", en: "Oblivious", d: { ja: "めろめろ・ちょうふを受けない", en: "Immune to infatuation and taunt" } },
    moxie:        { ja: "じしんかじょう", en: "Moxie", d: { ja: "倒すと攻撃が上がる", en: "Raises Attack after a KO" } },
    toxicdebris:  { ja: "どくのさいし", en: "Toxic Debris", d: { ja: "物理技を受けるとどくびしをまく", en: "Sets Toxic Spikes when hit" } },
    thermalexchange: { ja: "サーマルチェンジ", en: "Thermal Exchange", d: { ja: "ほのお技で攻撃が上がる・やけどにならない", en: "Boosts Attack from Fire; burn immune" } },
    minsblessing: { ja: "もちもちもち", en: "Mind's Eye", d: { ja: "回避を無視し、ノーマル・かくとうがゴーストに当たる", en: "Ignores evasion; hits Ghosts" } },
    vitalspirit:  { ja: "やるき", en: "Vital Spirit", d: { ja: "ねむりにならない", en: "Prevents sleep" } },
    sandrush:     { ja: "すなかき", en: "Sand Rush", d: { ja: "砂嵐で素早さが2倍", en: "Doubles Speed in a sandstorm" } },
    moldbreaker:  { ja: "かたやぶり", en: "Mold Breaker", d: { ja: "相手の特性を無視する", en: "Ignores the target's Ability" } },
    flamebody:    { ja: "やけどのからだ", en: "Flame Body", d: { ja: "接触するとやけどにすることがある", en: "May burn on contact" } },
    swarm:        { ja: "むしのしらせ", en: "Swarm", d: { ja: "ピンチでむし技が強くなる", en: "Boosts Bug moves when low HP" } },
    marvelscale:  { ja: "ふしぎなうろこ", en: "Marvel Scale", d: { ja: "状態異常のとき防御が上がる", en: "Boosts Defense when statused" } },
    gluttony:     { ja: "くいしんぼう", en: "Gluttony", d: { ja: "きのみを早く使う", en: "Eats Berries earlier" } },
    healer:       { ja: "いやしのこころ", en: "Healer", d: { ja: "味方の状態異常を治すことがある", en: "May cure ally status" } },
    weakarmor:    { ja: "ふいうち", en: "Weak Armor", d: { ja: "物理技で防御が下がり素早さが上がる", en: "Lowers Defense, raises Speed" } },
    magnetpull:   { ja: "じりょく", en: "Magnet Pull", d: { ja: "はがねを逃がせない", en: "Traps Steel types" } },
    shellarmor:   { ja: "シェルアーマー", en: "Shell Armor", d: { ja: "急所に当たらない", en: "Blocks critical hits" } },
    gooey:        { ja: "ヌメヌメ", en: "Gooey", d: { ja: "接触した相手の素早さを下げる", en: "Lowers Speed on contact" } },
    snowcloak:    { ja: "ゆきかくれ", en: "Snow Cloak", d: { ja: "雪で回避率が上がる", en: "Raises evasion in snow" } },
    icebody:      { ja: "アイスボディ", en: "Ice Body", d: { ja: "雪でHPが回復する", en: "Heals in snow" } },
    pixilate:     { ja: "フェアリースキン", en: "Pixilate", d: { ja: "ノーマル技がフェアリーになる", en: "Normal moves become Fairy" } },
    cutecharm:    { ja: "めろめろボディ", en: "Cute Charm", d: { ja: "接触するとめろめろにすることがある", en: "May infatuate on contact" } },
    magicbounce:  { ja: "マジックミラー", en: "Magic Bounce", d: { ja: "変化技を跡ね返す", en: "Reflects status moves" } },
    download:     { ja: "ダウンロード", en: "Download", d: { ja: "相手の弱いところに合わせて強くなる", en: "Boosts the better attacking stat" } },
    armortail:    { ja: "アーマーテール", en: "Armor Tail", d: { ja: "先制技を受けない", en: "Blocks priority moves" } },
    raindish:     { ja: "あめうけざら", en: "Rain Dish", d: { ja: "雨でHPが回復する", en: "Heals in rain" } },
    strongjaw:    { ja: "ストロングジョー", en: "Strong Jaw", d: { ja: "かみつく技が強くなる", en: "Powers up biting moves" } },
    rivalry:      { ja: "とうそうしん", en: "Rivalry", d: { ja: "同じ性別に強い", en: "Stronger against the same gender" } },
    mycelium:     { ja: "きんしのパワー", en: "Mycelium Might", d: { ja: "変化技が必ずあとになるが特性を無視する", en: "Status moves go last but ignore Abilities" } },
    staticc:      { ja: "ていでんき", en: "Static", d: { ja: "接触するとまひにすることがある", en: "May paralyze on contact" } },
    electromorphosis: { ja: "でんきにかえる", en: "Electromorphosis", d: { ja: "技を受けると次のでんき技が強くなる", en: "Charges Electric moves when hit" } },
    multitype:    { ja: "マルチタイプ", en: "Multitype", d: { ja: "持ち物でタイプが変わる", en: "Type changes with its item" } },
    fairyaura:    { ja: "フェアリーオーラ", en: "Fairy Aura", d: { ja: "場のフェアリー技が強くなる", en: "Powers up all Fairy moves" } },
    darkaura:     { ja: "ダークオーラ", en: "Dark Aura", d: { ja: "場のあく技が強くなる", en: "Powers up all Dark moves" } },
    teravolt:     { ja: "テラボルテージ", en: "Teravolt", d: { ja: "相手の特性を無視する", en: "Ignores the target's Ability" } },
    turboblaze:   { ja: "ターボブレイズ", en: "Turboblaze", d: { ja: "相手の特性を無視する", en: "Ignores the target's Ability" } },
    fullmetalbody:{ ja: "メタルプロテクト", en: "Full Metal Body", d: { ja: "能力を下げられない", en: "Prevents stat drops" } },
    shadowshield: { ja: "ファンタガード", en: "Shadow Shield", d: { ja: "HP満タンのとき受けるダメージが半分", en: "Halves damage at full HP" } },
    airlock:      { ja: "エアロック", en: "Air Lock", d: { ja: "天候の効果を消す", en: "Negates weather effects" } },
    stalwart:     { ja: "ばんけん", en: "Stalwart", d: { ja: "技の向きが変えられない", en: "Ignores redirection" } },
    stamina:      { ja: "スタミナ", en: "Stamina", d: { ja: "技を受けると防御が上がる", en: "Raises Defense when hit" } },
    solarpower:   { ja: "さんぷわー", en: "Solar Power", d: { ja: "晴れで特攻が上がる（HPが減る）", en: "Boosts Sp.Atk in sun (loses HP)" } },
    /* ══ ★★ 2026-09-10 メガシンカ・ゲンシカイキの特性 ══
       ★ eff が付いているものだけが<b>相性の計算に効く</b>。
         それ以外は説明だけ（画面には出るが、点数は動かない）。 */
    toughclaws:   { ja: "かたいツメ", en: "Tough Claws", d: { ja: "接触する技の威力が上がる", en: "Powers up contact moves" } },
    shadowtag:    { ja: "かげふみ", en: "Shadow Tag", d: { ja: "相手を逃がさない（交代できない）", en: "The foe cannot switch out" } },
    steadfast:    { ja: "ふくつのこころ", en: "Steadfast", d: { ja: "ひるむと素早さが上がる", en: "Raises Speed when it flinches" } },
    insomnia:     { ja: "ふみん", en: "Insomnia", d: { ja: "ねむりにならない", en: "Prevents sleep" } },
    adaptability: { ja: "てきおうりょく", en: "Adaptability", d: { ja: "自分と同じタイプの技がさらに強くなる", en: "Powers up same-type moves further" } },
    sandforce:    { ja: "すなのちから", en: "Sand Force", d: { ja: "砂嵐で いわ・じめん・はがね の技が強くなる", en: "Boosts Rock/Ground/Steel in a sandstorm" } },
    aerilate:     { ja: "スカイスキン", en: "Aerilate", eff: "skin:flying", d: { ja: "ノーマル技が<b>ひこう</b>になり、威力も上がる", en: "Normal moves become Flying and are boosted" } },
    /* ★ ゲンシカイキの天候は<b>ほのお／みずを完全に無効</b>にする。相性の計算に効く。 */
    primordialsea: { ja: "はじまりのうみ", en: "Primordial Sea", eff: "immune:fire",
      d: { ja: "大雨で<b>ほのお技が発動しない</b>（無効）", en: "Heavy rain — Fire moves fail" } },
    desolateland: { ja: "おわりのだいち", en: "Desolate Land", eff: "immune:water",
      d: { ja: "大日照りで<b>みず技が発動しない</b>（無効）", en: "Harsh sun — Water moves fail" } },
    /* ★ デルタストリームは「ひこうの弱点を打ち消す」。専用のあつかいが要るので eff は delta。 */
    deltastream:  { ja: "デルタストリーム", en: "Delta Stream", eff: "delta",
      d: { ja: "乱気流で<b>ひこうタイプの弱点が無くなる</b>", en: "Strong winds remove Flying's weaknesses" } },
  };

  /* ══════════ ⑤ 技 ══════════
     [タイプ, 分類(phys/spec/status), 威力] */
  const MOVES = {
    "10まんボルト":     { ja: "10まんボルト", en: "Thunderbolt", t: "electric", c: "spec", p: 90 },
    "かみなり":         { ja: "かみなり", en: "Thunder", t: "electric", c: "spec", p: 110 },
    "ボルトチェンジ":   { ja: "ボルトチェンジ", en: "Volt Switch", t: "electric", c: "spec", p: 70 },
    "ワイルドボルト":   { ja: "ワイルドボルト", en: "Wild Charge", t: "electric", c: "phys", p: 90 },
    "でんじは":         { ja: "でんじは", en: "Thunder Wave", t: "electric", c: "status", p: 0 },
    "かえんほうしゃ":   { ja: "かえんほうしゃ", en: "Flamethrower", t: "fire", c: "spec", p: 90 },
    "だいもんじ":       { ja: "だいもんじ", en: "Fire Blast", t: "fire", c: "spec", p: 110 },
    "オーバーヒート":   { ja: "オーバーヒート", en: "Overheat", t: "fire", c: "spec", p: 130 },
    "フレアドライブ":   { ja: "フレアドライブ", en: "Flare Blitz", t: "fire", c: "phys", p: 120 },
    "ニトロチャージ":   { ja: "ニトロチャージ", en: "Flame Charge", t: "fire", c: "phys", p: 50 },
    "ハイドロポンプ":   { ja: "ハイドロポンプ", en: "Hydro Pump", t: "water", c: "spec", p: 110 },
    "なみのり":         { ja: "なみのり", en: "Surf", t: "water", c: "spec", p: 90 },
    "たきのぼり":       { ja: "たきのぼり", en: "Waterfall", t: "water", c: "phys", p: 80 },
    "アクアジェット":   { ja: "アクアジェット", en: "Aqua Jet", t: "water", c: "phys", p: 40 },
    "アクアブレイク":   { ja: "アクアブレイク", en: "Aqua Cutter", t: "water", c: "phys", p: 70 },
    "エナジーボール":   { ja: "エナジーボール", en: "Energy Ball", t: "grass", c: "spec", p: 90 },
    "リーフブレード":   { ja: "リーフブレード", en: "Leaf Blade", t: "grass", c: "phys", p: 90 },
    "ウッドハンマー":   { ja: "ウッドハンマー", en: "Wood Hammer", t: "grass", c: "phys", p: 120 },
    "タネばくだん":     { ja: "タネばくだん", en: "Seed Bomb", t: "grass", c: "phys", p: 80 },
    "キノコのほうし":   { ja: "キノコのほうし", en: "Spore", t: "grass", c: "status", p: 0 },
    "れいとうビーム":   { ja: "れいとうビーム", en: "Ice Beam", t: "ice", c: "spec", p: 90 },
    "ふぶき":           { ja: "ふぶき", en: "Blizzard", t: "ice", c: "spec", p: 110 },
    "つららおとし":     { ja: "つららおとし", en: "Icicle Crash", t: "ice", c: "phys", p: 85 },
    "こおりのつぶて":   { ja: "こおりのつぶて", en: "Ice Shard", t: "ice", c: "phys", p: 40 },
    "インファイト":     { ja: "インファイト", en: "Close Combat", t: "fighting", c: "phys", p: 120 },
    "ドレインパンチ":   { ja: "ドレインパンチ", en: "Drain Punch", t: "fighting", c: "phys", p: 75 },
    "きあいだま":   { ja: "きあいだま", en: "Focus Blast", t: "fighting", c: "spec", p: 120 },
    "とびひざげり":     { ja: "とびひざげり", en: "High Jump Kick", t: "fighting", c: "phys", p: 130 },
    "ばくれつパンチ":   { ja: "ばくれつパンチ", en: "Dynamic Punch", t: "fighting", c: "phys", p: 100 },
    "ヘドロばくだん":   { ja: "ヘドロばくだん", en: "Sludge Bomb", t: "poison", c: "spec", p: 90 },
    "どくどく":         { ja: "どくどく", en: "Toxic", t: "poison", c: "status", p: 0 },
    "ダストシュート":   { ja: "ダストシュート", en: "Gunk Shot", t: "poison", c: "phys", p: 120 },
    "じしん":           { ja: "じしん", en: "Earthquake", t: "ground", c: "phys", p: 100 },
    "だいちのちから":   { ja: "だいちのちから", en: "Earth Power", t: "ground", c: "spec", p: 90 },
    "じならし":         { ja: "じならし", en: "Bulldoze", t: "ground", c: "phys", p: 60 },
    "ドリルライナー":   { ja: "ドリルライナー", en: "Drill Run", t: "ground", c: "phys", p: 80 },
    "ぼうふう":         { ja: "ぼうふう", en: "Hurricane", t: "flying", c: "spec", p: 110 },
    "ブレイブバード":   { ja: "ブレイブバード", en: "Brave Bird", t: "flying", c: "phys", p: 120 },
    "エアスラッシュ":   { ja: "エアスラッシュ", en: "Air Slash", t: "flying", c: "spec", p: 75 },
    "アクロバット":     { ja: "アクロバット", en: "Acrobatics", t: "flying", c: "phys", p: 55 },
    "サイコキネシス":   { ja: "サイコキネシス", en: "Psychic", t: "psychic", c: "spec", p: 90 },
    "サイコショック":   { ja: "サイコショック", en: "Psyshock", t: "psychic", c: "spec", p: 80 },
    "ワイドフォース":   { ja: "ワイドフォース", en: "Expanding Force", t: "psychic", c: "spec", p: 80 },
    "トリックルーム":   { ja: "トリックルーム", en: "Trick Room", t: "psychic", c: "status", p: 0 },
    "とんぼがえり":     { ja: "とんぼがえり", en: "U-turn", t: "bug", c: "phys", p: 70 },
    "むしのさざめき":   { ja: "むしのさざめき", en: "Bug Buzz", t: "bug", c: "spec", p: 90 },
    "シザークロス":     { ja: "シザークロス", en: "X-Scissor", t: "bug", c: "phys", p: 80 },
    "ストーンエッジ":   { ja: "ストーンエッジ", en: "Stone Edge", t: "rock", c: "phys", p: 100 },
    "いわなだれ":       { ja: "いわなだれ", en: "Rock Slide", t: "rock", c: "phys", p: 75 },
    "パワージェム":     { ja: "パワージェム", en: "Power Gem", t: "rock", c: "spec", p: 80 },
    "シャドーボール":   { ja: "シャドーボール", en: "Shadow Ball", t: "ghost", c: "spec", p: 80 },
    "シャドークロー":   { ja: "シャドークロー", en: "Shadow Claw", t: "ghost", c: "phys", p: 70 },
    "ゴーストダイブ":   { ja: "ゴーストダイブ", en: "Phantom Force", t: "ghost", c: "phys", p: 90 },
    "りゅうせいぐん":   { ja: "りゅうせいぐん", en: "Draco Meteor", t: "dragon", c: "spec", p: 130 },
    "げきりん":         { ja: "げきりん", en: "Outrage", t: "dragon", c: "phys", p: 120 },
    "ドラゴンクロー":   { ja: "ドラゴンクロー", en: "Dragon Claw", t: "dragon", c: "phys", p: 80 },
    "りゅうのまい":     { ja: "りゅうのまい", en: "Dragon Dance", t: "dragon", c: "status", p: 0 },
    "あくのはどう":     { ja: "あくのはどう", en: "Dark Pulse", t: "dark", c: "spec", p: 80 },
    "かみくだく":       { ja: "かみくだく", en: "Crunch", t: "dark", c: "phys", p: 80 },
    "はたきおとす":     { ja: "はたきおとす", en: "Knock Off", t: "dark", c: "phys", p: 65 },
    "ふいうち":         { ja: "ふいうち", en: "Sucker Punch", t: "dark", c: "phys", p: 70 },
    "アイアンヘッド":   { ja: "アイアンヘッド", en: "Iron Head", t: "steel", c: "phys", p: 80 },
    "ラスターカノン":   { ja: "ラスターカノン", en: "Flash Cannon", t: "steel", c: "spec", p: 80 },
    "バレットパンチ":   { ja: "バレットパンチ", en: "Bullet Punch", t: "steel", c: "phys", p: 40 },
    "ボディプレス":     { ja: "ボディプレス", en: "Body Press", t: "fighting", c: "phys", p: 80 },
    "ムーンフォース":   { ja: "ムーンフォース", en: "Moonblast", t: "fairy", c: "spec", p: 95 },
    "マジカルシャイン": { ja: "マジカルシャイン", en: "Dazzling Gleam", t: "fairy", c: "spec", p: 80 },
    "じゃれつく":       { ja: "じゃれつく", en: "Play Rough", t: "fairy", c: "phys", p: 90 },
    "みがわり":         { ja: "みがわり", en: "Substitute", t: "normal", c: "status", p: 0 },
    "まもる":           { ja: "まもる", en: "Protect", t: "normal", c: "status", p: 0 },
    "つるぎのまい":     { ja: "つるぎのまい", en: "Swords Dance", t: "normal", c: "status", p: 0 },
    "でんこうせっか":   { ja: "でんこうせっか", en: "Quick Attack", t: "normal", c: "phys", p: 40 },
    "しんそく":         { ja: "しんそく", en: "Extreme Speed", t: "normal", c: "phys", p: 80 },
    "はかいこうせん":   { ja: "はかいこうせん", en: "Hyper Beam", t: "normal", c: "spec", p: 150 },
    "じこさいせい":     { ja: "じこさいせい", en: "Recover", t: "normal", c: "status", p: 0 },
    "はねやすめ":       { ja: "はねやすめ", en: "Roost", t: "flying", c: "status", p: 0 },
    "ステルスロック":   { ja: "ステルスロック", en: "Stealth Rock", t: "rock", c: "status", p: 0 },
    "おいかぜ":         { ja: "おいかぜ", en: "Tailwind", t: "flying", c: "status", p: 0 },
    "ねこだまし":       { ja: "ねこだまし", en: "Fake Out", t: "normal", c: "phys", p: 40 },
    "ワイドガード":       { ja: "ワイドガード", en: "Wide Guard", t: "rock", c: "status", p: 0 },
    /* ── 上のポケモンが覚えている技のうち、まだ並んでいなかったもの ──
       ★ ここに無い技は<b>攻撃範囲の分析に入らない</b>ので、必ず足すこと。 */
    "ジャイロボール": { ja: "ジャイロボール", en: "Gyro Ball", t: "steel", c: "phys", p: 80 },
    "ヘビーボンバー": { ja: "ヘビーボンバー", en: "Heavy Slam", t: "steel", c: "phys", p: 100 },
    "しおづけ": { ja: "しおづけ", en: "Salt Cure", t: "rock", c: "phys", p: 40 },
    "ブラッドムーン": { ja: "ブラッドムーン", en: "Blood Moon", t: "normal", c: "spec", p: 140 },
    "はいすいのじん": { ja: "はいすいのじん", en: "No Retreat", t: "fighting", c: "status", p: 0 },
    "ツタこんぼう": { ja: "ツタこんぼう", en: "Ivy Cudgel", t: "grass", c: "phys", p: 100 },
    "アストラルビット": { ja: "アストラルビット", en: "Astral Barrage", t: "ghost", c: "spec", p: 120 },
    "グレイシアレイジ": { ja: "グレイシアレイジ", en: "Glacial Lance", t: "ice", c: "phys", p: 120 },
    "きょじゅざん": { ja: "きょじゅざん", en: "Behemoth Blade", t: "steel", c: "phys", p: 100 },
    "きょじゅうだん": { ja: "きょじゅうだん", en: "Behemoth Bash", t: "steel", c: "phys", p: 100 },
    "でんげきくちばし": { ja: "でんげきくちばし", en: "Electro Drift", t: "electric", c: "spec", p: 100 },
    "しおふき": { ja: "しおふき", en: "Water Spout", t: "water", c: "spec", p: 150 },
    "がんせきふうじ": { ja: "がんせきふうじ", en: "Rock Tomb", t: "rock", c: "phys", p: 60 },
    "エアロブラスト": { ja: "エアロブラスト", en: "Aeroblast", t: "flying", c: "spec", p: 100 },
    "せいなるほのお": { ja: "せいなるほのお", en: "Sacred Fire", t: "fire", c: "phys", p: 100 },
    "ときのほうこう": { ja: "ときのほうこう", en: "Roar of Time", t: "dragon", c: "spec", p: 150 },
    "あくううせつだん": { ja: "あくううせつだん", en: "Spacial Rend", t: "dragon", c: "spec", p: 100 },
    "ジオコントロール": { ja: "ジオコントロール", en: "Geomancy", t: "fairy", c: "status", p: 0 },
    "デスウイング": { ja: "デスウイング", en: "Oblivion Wing", t: "flying", c: "spec", p: 80 },
    "フォトンゲイザー": { ja: "フォトンゲイザー", en: "Photon Geyser", t: "psychic", c: "spec", p: 100 },
    "おにび": { ja: "おにび", en: "Will-O-Wisp", t: "fire", c: "status", p: 0 },
    "のろい": { ja: "のろい", en: "Curse", t: "ghost", c: "status", p: 0 },
    "はらだいこ": { ja: "はらだいこ", en: "Belly Drum", t: "normal", c: "status", p: 0 },
    "ちきゅうなげ": { ja: "ちきゅうなげ", en: "Seismic Toss", t: "fighting", c: "phys", p: 1 },
    "タマゴうみ": { ja: "タマゴうみ", en: "Soft-Boiled", t: "normal", c: "status", p: 0 },
    "オーロラベール": { ja: "オーロラベール", en: "Aurora Veil", t: "ice", c: "status", p: 0 },
    "ハイパーボイス": { ja: "ハイパーボイス", en: "Hyper Voice", t: "normal", c: "spec", p: 90 },
    "あくび": { ja: "あくび", en: "Yawn", t: "normal", c: "status", p: 0 },
    "トライアタック": { ja: "トライアタック", en: "Tri Attack", t: "normal", c: "spec", p: 80 },
    "フォローミー": { ja: "フォローミー", en: "Follow Me", t: "normal", c: "status", p: 0 },
    "ふんか": { ja: "ふんか", en: "Eruption", t: "fire", c: "spec", p: 150 },
    "エラがみ": { ja: "エラがみ", en: "Fishious Rend", t: "water", c: "phys", p: 85 },
    "ライジングボルト": { ja: "ライジングボルト", en: "Rising Voltage", t: "electric", c: "spec", p: 70 },
    "ふくろだたき": { ja: "ふくろだたき", en: "Beat Up", t: "dark", c: "phys", p: 1 },
    "ヘドロウェーブ": { ja: "ヘドロウェーブ", en: "Sludge Wave", t: "poison", c: "spec", p: 95 },
    "さばきのつぶて": { ja: "さばきのつぶて", en: "Judgment", t: "normal", c: "spec", p: 100 },
    "ねっとう": { ja: "ねっとう", en: "Scald", t: "water", c: "spec", p: 80 },
    "メテオドライブ": { ja: "メテオドライブ", en: "Sunsteel Strike", t: "steel", c: "phys", p: 100 },
    "シャドーレイ": { ja: "シャドーレイ", en: "Moongeist Beam", t: "ghost", c: "spec", p: 100 },
    "クロスサンダー": { ja: "クロスサンダー", en: "Bolt Strike", t: "electric", c: "phys", p: 130 },
    "クロスフレイム": { ja: "クロスフレイム", en: "Blue Flare", t: "fire", c: "spec", p: 130 },
    "ダイマックスほう": { ja: "ダイマックスほう", en: "Dynamax Cannon", t: "dragon", c: "spec", p: 100 },
    "ちょうのまい": { ja: "ちょうのまい", en: "Quiver Dance", t: "bug", c: "status", p: 0 },
    "アクセルブレイク": { ja: "アクセルブレイク", en: "Collision Course", t: "fighting", c: "phys", p: 100 },
    "いばる": { ja: "いばる", en: "Swagger", t: "normal", c: "status", p: 0 },
    "めいそう": { ja: "めいそう", en: "Calm Mind", t: "psychic", c: "status", p: 0 },
  };

  /* ══════════ ⑥ 持ち物 ══════════ */
  const ITEMS = {
    leftovers:   { ja: "たべのこし",       en: "Leftovers" },
    choiceband:  { ja: "こだわりハチマキ", en: "Choice Band" },
    choicespecs: { ja: "こだわりメガネ",   en: "Choice Specs" },
    choicescarf: { ja: "こだわりスカーフ", en: "Choice Scarf" },
    lifeorb:     { ja: "いのちのたま",     en: "Life Orb" },
    focussash:   { ja: "きあいのタスキ",   en: "Focus Sash" },
    assaultvest: { ja: "とつげきチョッキ", en: "Assault Vest" },
    rockyhelmet: { ja: "ゴツゴツメット",   en: "Rocky Helmet" },
    sitrusberry: { ja: "オボンのみ",       en: "Sitrus Berry" },
    heavydutyboots: { ja: "あつぞこブーツ", en: "Heavy-Duty Boots" },
    weaknesspolicy: { ja: "じゃくてんほけん", en: "Weakness Policy" },
    lightclay:   { ja: "ひかりのねんど",   en: "Light Clay" },
    covertcloak: { ja: "ぼうごパット",     en: "Covert Cloak" },
    boosterenergy: { ja: "ブーストエナジー", en: "Booster Energy" },
    clearamulet: { ja: "クリアチャーム",   en: "Clear Amulet" },
    safetygoggles: { ja: "ぼうじんゴーグル", en: "Safety Goggles" },
    mentalherb:  { ja: "メンタルハーブ",   en: "Mental Herb" },
    airballoon:  { ja: "ふうせん",         en: "Air Balloon" },
    expertbelt:  { ja: "たつじんのおび",   en: "Expert Belt" },
    eviolite:    { ja: "しんかのきせき",   en: "Eviolite" },
  };

  /* ══════════ ⑦ ポケモン ══════════
     圧縮した配列 → 下でオブジェクトに展開する。
     [ id, ja, en, type1, type2, hp, atk, def, spa, spd, spe, gen,
       [特性…], [技…], [持ち物…], [役割…], 使用率%, 勝率%, 前週比 ] */
  const RAW = [
    ["garchomp","ガブリアス","Garchomp","dragon","ground",108,130,95,80,85,102,4,["roughskin","sandveil"],["じしん","げきりん","ストーンエッジ","つるぎのまい"],["choiceband","lifeorb","focussash"],["sweeper","setup"],14.2,53.8,1.4],
    ["dragonite","カイリュー","Dragonite","dragon","flying",91,134,95,100,100,80,1,["multiscale","innerfocus"],["しんそく","げきりん","じしん","りゅうのまい"],["heavydutyboots","choiceband","lifeorb"],["tank","setup"],16.8,55.1,2.2],
    ["mimikyu","ミミッキュ","Mimikyu","ghost","fairy",55,90,80,50,105,96,7,["disguise"],["じゃれつく","シャドークロー","つるぎのまい","でんこうせっか"],["lifeorb","focussash"],["sweeper","setup"],11.3,52.0,-0.6],
    ["gholdengo","サーフゴー","Gholdengo","steel","ghost",87,60,95,133,91,84,9,["goodasgold"],["シャドーボール","ラスターカノン","まもる","みがわり"],["leftovers","choicespecs","airballoon"],["wall","sweeper"],13.9,54.4,0.8],
    ["fluttermane","ハバタクカミ","Flutter Mane","ghost","fairy",55,55,55,135,135,135,9,["protosynthesis"],["ムーンフォース","シャドーボール","まもる","みがわり"],["boosterenergy","choicespecs","focussash"],["speed","sweeper"],18.6,56.3,1.1],
    ["ironvaliant","テツノブジン","Iron Valiant","fairy","fighting",74,130,90,120,60,116,9,["quarkdrive"],["ムーンフォース","インファイト","つるぎのまい","ふいうち"],["boosterenergy","lifeorb","choicescarf"],["sweeper","speed"],9.4,51.2,-0.9],
    ["roaringmoon","トドロクツキ","Roaring Moon","dragon","dark",105,139,71,55,101,119,9,["protosynthesis"],["げきりん","かみくだく","じしん","りゅうのまい"],["boosterenergy","choiceband","lifeorb"],["sweeper","setup"],10.1,52.9,0.4],
    ["ironhands","テツノカイナ","Iron Hands","fighting","electric",154,140,108,50,68,50,9,["quarkdrive"],["ドレインパンチ","ワイルドボルト","ねこだまし","まもる"],["assaultvest","boosterenergy","sitrusberry"],["tank","wall"],12.7,53.5,0.2],
    ["kingambit","ドドゲザン","Kingambit","dark","steel",100,135,120,60,85,50,9,["supremeoverlord","defiant"],["ふいうち","アイアンヘッド","つるぎのまい","はたきおとす"],["leftovers","choiceband","lifeorb"],["tank","setup"],15.2,55.7,1.9],
    ["chienpao","パオジアン","Chien-Pao","dark","ice",80,120,80,90,65,135,9,["swordofruin"],["つららおとし","はたきおとす","こおりのつぶて","つるぎのまい"],["focussash","choiceband","lifeorb"],["speed","sweeper"],11.8,53.1,-0.3],
    ["tinglu","ディンルー","Ting-Lu","dark","ground",155,110,125,55,80,45,9,["vesselofruin"],["じしん","はたきおとす","ステルスロック","ボディプレス"],["leftovers","assaultvest","rockyhelmet"],["wall","pivot"],8.9,51.8,0.5],
    ["chiyu","イーユイ","Chi-Yu","dark","fire",55,80,80,135,120,100,9,["beadsofruin"],["オーバーヒート","あくのはどう","かえんほうしゃ","まもる"],["choicescarf","choicespecs","focussash"],["sweeper","speed"],7.6,50.9,-1.2],
    ["dragapult","ドラパルト","Dragapult","dragon","ghost",88,120,75,100,75,142,8,["infiltrator","clearbody"],["シャドーボール","りゅうせいぐん","とんぼがえり","ドラゴンクロー"],["choicespecs","choiceband","heavydutyboots"],["speed","pivot"],13.1,53.3,0.7],
    ["urshifusingle","ウーラオス（いちげき）","Urshifu (Single Strike)","fighting","dark",100,130,100,63,60,97,8,["unseenfist"],["インファイト","かみくだく","ふいうち","つるぎのまい"],["choiceband","focussash","lifeorb"],["sweeper"],9.8,52.4,0.1],
    ["urshifurapid","ウーラオス（れんげき）","Urshifu (Rapid Strike)","fighting","water",100,130,100,63,60,97,8,["unseenfist"],["インファイト","アクアブレイク","はたきおとす","まもる"],["choiceband","focussash","choicescarf"],["sweeper"],12.4,54.0,1.0],
    ["incineroar","ガオガエン","Incineroar","fire","dark",95,115,90,80,90,60,7,["intimidate","blaze"],["ねこだまし","フレアドライブ","はたきおとす","まもる"],["assaultvest","sitrusberry","rockyhelmet"],["support","pivot"],21.4,54.9,0.6],
    ["rillaboom","ゴリランダー","Rillaboom","grass",null,100,125,90,60,70,85,8,["grassysurge","overgrow"],["ウッドハンマー","ねこだまし","はたきおとす","まもる"],["assaultvest","choiceband","sitrusberry"],["tank","support"],14.6,53.6,-0.2],
    ["amoonguss","モロバレル","Amoonguss","grass","poison",114,85,70,85,80,30,5,["regenerator"],["キノコのほうし","エナジーボール","まもる","どくどく"],["sitrusberry","rockyhelmet","covertcloak"],["wall","support"],17.2,52.7,0.3],
    ["landorust","ランドロス（霊獣）","Landorus-Therian","ground","flying",89,145,90,105,80,91,5,["intimidate"],["じしん","いわなだれ","とんぼがえり","まもる"],["assaultvest","choicescarf","rockyhelmet"],["pivot","support"],19.3,54.2,1.3],
    ["tornadust","トルネロス（霊獣）","Tornadus-Therian","flying",null,79,100,80,110,90,121,5,["regenerator"],["ぼうふう","おいかぜ","はたきおとす","まもる"],["heavydutyboots","covertcloak","sitrusberry"],["support","speed"],10.7,52.2,0.9],
    ["toxapex","ドヒドイデ","Toxapex","poison","water",50,63,152,53,142,35,7,["regenerator"],["どくどく","じこさいせい","ヘドロばくだん","まもる"],["leftovers","rockyhelmet","heavydutyboots"],["wall"],8.4,51.1,-0.4],
    ["corviknight","アーマーガア","Corviknight","flying","steel",98,87,105,53,85,67,8,["pressure","mirrorarmor"],["ブレイブバード","ボディプレス","はねやすめ","はたきおとす"],["leftovers","rockyhelmet","heavydutyboots"],["wall","pivot"],9.1,51.5,-0.7],
    ["ferrothorn","ナットレイ","Ferrothorn","grass","steel",74,94,131,54,116,20,5,["ironbarbs"],["ジャイロボール","ステルスロック","はたきおとす","タネばくだん"],["leftovers","rockyhelmet"],["wall"],6.2,50.4,-0.5],
    ["heatran","ヒードラン","Heatran","fire","steel",91,90,106,130,106,77,4,["flashfire"],["だいもんじ","だいちのちから","まもる","ステルスロック"],["leftovers","choicespecs","airballoon"],["wall","sweeper"],7.8,51.9,0.2],
    ["zapdos","サンダー","Zapdos","electric","flying",90,90,85,125,90,100,1,["static","pressure"],["10まんボルト","ぼうふう","はねやすめ","でんじは"],["heavydutyboots","leftovers","choicespecs"],["wall","pivot"],8.6,52.1,0.4],
    ["tapukoko","カプ・コケコ","Tapu Koko","electric","fairy",70,115,85,95,75,130,7,["electricsurge"],["10まんボルト","マジカルシャイン","ボルトチェンジ","まもる"],["lifeorb","choicespecs","focussash"],["speed","support"],7.2,51.4,-0.8],
    ["tapufini","カプ・レヒレ","Tapu Fini","water","fairy",70,75,115,95,130,85,7,["mistysurge"],["ムーンフォース","なみのり","まもる","じこさいせい"],["leftovers","sitrusberry","assaultvest"],["wall","support"],10.4,52.6,0.6],
    ["tapulele","カプ・テテフ","Tapu Lele","psychic","fairy",70,85,75,130,115,95,7,["psychicsurge"],["ワイドフォース","ムーンフォース","サイコショック","まもる"],["choicespecs","lifeorb","sitrusberry"],["sweeper","support"],6.8,50.7,-0.3],
    ["tapubulu","カプ・ブルル","Tapu Bulu","grass","fairy",70,130,115,85,95,75,7,["grassysurge"],["ウッドハンマー","じゃれつく","まもる","つるぎのまい"],["assaultvest","choiceband","sitrusberry"],["tank"],5.9,50.2,-0.1],
    ["kartana","カミツルギ","Kartana","grass","steel",59,181,131,59,31,109,7,["beastboost"],["リーフブレード","アイアンヘッド","つるぎのまい","はたきおとす"],["focussash","choicescarf","lifeorb"],["sweeper","speed"],6.4,51.0,0.3],
    ["celesteela","テッカグヤ","Celesteela","steel","flying",97,101,103,107,101,61,7,["beastboost"],["ヘビーボンバー","エアスラッシュ","まもる","どくどく"],["leftovers","assaultvest","choicescarf"],["wall","tank"],5.1,50.1,-0.2],
    ["glimmora","キラフロル","Glimmora","rock","poison",83,55,90,130,81,86,9,["toxicdebris"],["パワージェム","ヘドロばくだん","ステルスロック","だいちのちから"],["focussash","lifeorb","airballoon"],["pivot","sweeper"],6.6,50.6,0.5],
    ["palafin","イルカマン","Palafin","water",null,100,160,97,106,87,100,9,["zerotohero"],["アクアジェット","インファイト","たきのぼり","まもる"],["choiceband","lifeorb","focussash"],["sweeper"],8.2,52.8,1.5],
    ["meowscarada","マスカーニャ","Meowscarada","grass","dark",76,110,70,81,70,123,9,["protean","overgrow"],["リーフブレード","はたきおとす","ふいうち","つるぎのまい"],["choiceband","focussash","lifeorb"],["speed","sweeper"],7.4,51.3,-0.4],
    ["skeledirge","ラウドボーン","Skeledirge","fire","ghost",104,75,100,110,75,66,9,["blaze","unaware"],["かえんほうしゃ","シャドーボール","じこさいせい","どくどく"],["heavydutyboots","leftovers","sitrusberry"],["wall","tank"],6.9,51.6,0.2],
    ["quaquaval","ウェーニバル","Quaquaval","water","fighting",85,120,80,85,75,85,9,["torrent","moxie"],["アクアブレイク","インファイト","はたきおとす","つるぎのまい"],["lifeorb","choiceband","focussash"],["sweeper","setup"],4.8,49.9,-0.3],
    ["baxcalibur","セグレイブ","Baxcalibur","dragon","ice",115,145,92,75,86,87,9,["thermalexchange"],["つららおとし","げきりん","じしん","りゅうのまい"],["lifeorb","choiceband","leftovers"],["sweeper","setup"],7.1,52.3,0.8],
    ["ursalunabm","ガチグマ（アカツキ）","Ursaluna (Bloodmoon)","ground","normal",113,70,120,135,65,52,9,["minsblessing"],["ブラッドムーン","だいちのちから","まもる","はいすいのじん"],["assaultvest","leftovers","choicespecs"],["tank","sweeper"],9.6,53.0,1.7],
    ["annihilape","コノヨザル","Annihilape","fighting","ghost",110,115,80,50,90,90,9,["vitalspirit","defiant"],["ドレインパンチ","ゴーストダイブ","はたきおとす","まもる"],["leftovers","choiceband","sitrusberry"],["tank","setup"],5.6,50.5,-0.6],
    ["garganacl","キョジオーン","Garganacl","rock",null,100,100,130,45,90,35,9,["purifyingsalt"],["しおづけ","じしん","まもる","ステルスロック"],["leftovers","rockyhelmet","covertcloak"],["wall"],6.1,51.2,0.4],
    ["dondozo","ヘイラッシャ","Dondozo","water",null,150,100,115,65,65,35,9,["unaware","oblivious"],["たきのぼり","ボディプレス","じこさいせい","のろい"],["leftovers","heavydutyboots","rockyhelmet"],["wall"],5.4,50.8,0.1],
    ["clodsire","ドオー","Clodsire","poison","ground",130,75,60,45,100,20,9,["waterabsorb","unaware"],["どくどく","じしん","じこさいせい","はたきおとす"],["leftovers","heavydutyboots"],["wall"],4.9,50.0,-0.2],
    ["ironbundle","テツノツツミ","Iron Bundle","ice","water",56,80,114,124,60,136,9,["quarkdrive"],["ふぶき","ハイドロポンプ","こおりのつぶて","まもる"],["boosterenergy","choicespecs","focussash"],["speed","sweeper"],8.8,52.5,0.9],
    ["archaludon","ブリジュラス","Archaludon","steel","dragon",90,105,130,125,65,85,9,["stamina","stalwart"],["ラスターカノン","でんげきくちばし","ボディプレス","まもる"],["assaultvest","leftovers","airballoon"],["wall","sweeper"],7.9,52.0,1.2],
    ["ogerpon","オーガポン","Ogerpon","grass",null,80,120,84,60,96,110,9,["defiant"],["ツタこんぼう","はたきおとす","つるぎのまい","まもる"],["leftovers","choiceband","focussash"],["sweeper","setup"],9.2,53.2,1.6],
    ["calyrexshadow","バドレックス（黒馬）","Calyrex-Shadow","psychic","ghost",100,85,80,165,100,150,8,["asoneshadow"],["アストラルビット","サイコキネシス","まもる","みがわり"],["focussash","choicespecs","lifeorb"],["speed","sweeper"],11.6,55.4,0.7],
    ["calyrexice","バドレックス（白馬）","Calyrex-Ice","psychic","ice",100,165,150,85,130,50,8,["asoneice"],["グレイシアレイジ","インファイト","まもる","トリックルーム"],["clearamulet","leftovers","assaultvest"],["tank","wall"],10.9,54.6,0.3],
    ["zacian","ザシアン","Zacian","fairy",null,92,130,115,80,115,138,8,["intrepidsword"],["きょじゅうざん","じゃれつく","インファイト","まもる"],["rustedsword","lifeorb","choiceband"],["speed","sweeper"],12.2,56.0,0.5],
    ["miraidon","ミライドン","Miraidon","electric","dragon",100,85,100,135,115,135,9,["hadronengine"],["でんげきくちばし","りゅうせいぐん","まもる","10まんボルト"],["choicespecs","lifeorb","boosterenergy"],["speed","sweeper"],13.4,56.8,1.0],
    ["koraidon","コライドン","Koraidon","fighting","dragon",100,135,115,85,100,135,9,["orichalcum"],["アクセルブレイク","げきりん","まもる","でんこうせっか"],["clearamulet","lifeorb","choiceband"],["speed","sweeper"],12.8,56.5,0.8],
    ["kyogre","カイオーガ","Kyogre","water",null,100,100,90,150,140,90,3,["drizzle"],["しおふき","ハイドロポンプ","れいとうビーム","まもる"],["choicescarf","choicespecs","leftovers"],["sweeper"],9.9,55.2,0.2],
    ["groudon","グラードン","Groudon","ground",null,100,150,140,100,90,90,3,["drought"],["じしん","がんせきふうじ","まもる","つるぎのまい"],["leftovers","assaultvest","clearamulet"],["tank","setup"],8.7,54.1,-0.1],
    ["rayquaza","レックウザ","Rayquaza","dragon","flying",105,150,90,150,90,95,3,["airlock"],["げきりん","しんそく","りゅうのまい","じしん"],["lifeorb","choiceband","focussash"],["sweeper","setup"],6.3,52.7,0.4],
    ["lugia","ルギア","Lugia","psychic","flying",106,90,130,90,154,110,2,["multiscale","pressure"],["エアロブラスト","はねやすめ","でんじは","まもる"],["heavydutyboots","leftovers","sitrusberry"],["wall","support"],4.6,50.3,-0.4],
    ["hooh","ホウオウ","Ho-Oh","fire","flying",106,130,90,110,154,90,2,["regenerator","pressure"],["せいなるほのお","ブレイブバード","はねやすめ","まもる"],["heavydutyboots","leftovers","assaultvest"],["tank","wall"],4.2,50.6,0.1],
    ["mewtwo","ミュウツー","Mewtwo","psychic",null,106,110,90,154,90,130,1,["pressure","unnerve"],["サイコキネシス","きあいだま","シャドーボール","まもる"],["lifeorb","choicespecs","focussash"],["speed","sweeper"],5.2,52.4,0.3],
    ["giratina","ギラティナ","Giratina","ghost","dragon",150,100,120,100,120,90,4,["pressure"],["シャドーボール","ドラゴンクロー","おにび","まもる"],["leftovers","rockyhelmet","covertcloak"],["wall"],4.4,50.9,-0.2],
    ["dialga","ディアルガ","Dialga","steel","dragon",100,120,120,150,100,90,4,["pressure"],["ときのほうこう","ラスターカノン","まもる","トリックルーム"],["leftovers","assaultvest","choicespecs"],["tank","wall"],4.7,51.7,0.2],
    ["palkia","パルキア","Palkia","water","dragon",90,120,100,150,120,100,4,["pressure"],["あくうせつだん","ハイドロポンプ","まもる","りゅうせいぐん"],["lifeorb","choicespecs","leftovers"],["sweeper"],4.1,51.0,0.0],
    ["xerneas","ゼルネアス","Xerneas","fairy",null,126,131,95,131,98,99,6,["fairyaura"],["ジオコントロール","ムーンフォース","まもる","じゃれつく"],["powerherb","clearamulet","leftovers"],["setup","sweeper"],7.7,54.8,0.6],
    ["yveltal","イベルタル","Yveltal","dark","flying",126,131,95,131,98,99,6,["darkaura"],["デスウイング","ぼうふう","まもる","はたきおとす"],["heavydutyboots","lifeorb","leftovers"],["tank","sweeper"],6.8,53.4,0.3],
    ["necrozmadm","ネクロズマ","Necrozma","psychic",null,97,107,101,127,89,79,7,["prismarmor"],["フォトンゲイザー","サイコキネシス","まもる","ステルスロック"],["leftovers","lifeorb","focussash"],["tank"],3.8,50.2,-0.3],
    ["tyranitar","バンギラス","Tyranitar","rock","dark",100,134,110,95,100,61,2,["sandstream"],["ストーンエッジ","かみくだく","じしん","ステルスロック"],["assaultvest","choiceband","leftovers"],["tank"],5.7,51.3,-0.5],
    ["metagross","メタグロス","Metagross","steel","psychic",80,135,130,95,90,70,3,["clearbody","lightmetal"],["アイアンヘッド","バレットパンチ","じしん","つるぎのまい"],["lifeorb","choiceband","assaultvest"],["tank"],4.3,50.4,-0.2],
    ["salamence","ボーマンダ","Salamence","dragon","flying",95,135,80,110,80,100,3,["intimidate","moxie"],["げきりん","じしん","りゅうせいぐん","りゅうのまい"],["lifeorb","choiceband","choicescarf"],["sweeper"],4.0,50.1,-0.6],
    ["gyarados","ギャラドス","Gyarados","water","flying",95,125,79,60,100,81,1,["intimidate","moxie"],["たきのぼり","じしん","りゅうのまい","はたきおとす"],["lifeorb","leftovers","choiceband"],["setup","sweeper"],4.5,50.7,0.1],
    ["charizard","リザードン","Charizard","fire","flying",78,84,78,109,85,100,1,["blaze","solarpower"],["かえんほうしゃ","エアスラッシュ","だいもんじ","まもる"],["heavydutyboots","choicespecs","lifeorb"],["sweeper"],5.0,49.8,-0.9],
    ["gengar","ゲンガー","Gengar","ghost","poison",60,65,60,130,75,110,1,["cursedbody"],["シャドーボール","ヘドロばくだん","きあいだま","みがわり"],["choicespecs","focussash","lifeorb"],["speed","sweeper"],3.9,49.6,-0.7],
    ["gardevoir","サーナイト","Gardevoir","psychic","fairy",68,65,65,125,115,80,3,["traceability","synchronize"],["ムーンフォース","サイコキネシス","まもる","マジカルシャイン"],["choicespecs","lifeorb","focussash"],["sweeper","support"],3.6,49.4,-0.4],
    ["lucario","ルカリオ","Lucario","fighting","steel",70,110,70,115,70,90,4,["innerfocus","justified"],["インファイト","バレットパンチ","つるぎのまい","しんそく"],["lifeorb","focussash","choiceband"],["sweeper"],3.4,49.2,-0.5],
    ["togekiss","トゲキッス","Togekiss","fairy","flying",85,50,95,120,115,80,4,["serenegrace","superluck"],["エアスラッシュ","ムーンフォース","おいかぜ","まもる"],["leftovers","sitrusberry","heavydutyboots"],["support","wall"],5.3,51.1,0.3],
    ["azumarill","マリルリ","Azumarill","water","fairy",100,50,80,60,80,50,2,["hugepower","thickfat"],["アクアジェット","じゃれつく","はらだいこ","たきのぼり"],["sitrusberry","choiceband","assaultvest"],["tank","setup"],4.6,50.5,0.2],
    ["whimsicott","エルフーン","Whimsicott","grass","fairy",60,67,85,77,75,116,5,["prankster","infiltrator"],["おいかぜ","いばる","エナジーボール","まもる"],["focussash","covertcloak","mentalherb"],["support","trick"],6.7,51.4,0.5],
    ["cresselia","クレセリア","Cresselia","psychic",null,120,70,120,75,130,85,4,["levitate"],["トリックルーム","サイコキネシス","じこさいせい","まもる"],["leftovers","sitrusberry","mentalherb"],["wall","support"],4.8,50.9,0.1],
    ["excadrill","ドリュウズ","Excadrill","ground","steel",110,135,60,50,65,88,5,["sandrush","moldbreaker"],["じしん","アイアンヘッド","いわなだれ","まもる"],["assaultvest","choiceband","focussash"],["sweeper"],5.5,51.0,-0.1],
    ["volcarona","ウルガモス","Volcarona","bug","fire",85,60,65,135,105,100,5,["flamebody","swarm"],["だいもんじ","むしのさざめき","ちょうのまい","まもる"],["heavydutyboots","lifeorb","leftovers"],["setup","sweeper"],4.2,50.3,-0.3],
    ["scizor","ハッサム","Scizor","bug","steel",70,130,100,55,80,65,2,["technician","lightmetal"],["バレットパンチ","とんぼがえり","つるぎのまい","はたきおとす"],["choiceband","leftovers","lifeorb"],["tank","pivot"],3.7,49.9,-0.2],
    ["breloom","キノガッサ","Breloom","grass","fighting",60,130,80,60,60,70,3,["technician","poisonheal"],["キノコのほうし","タネばくだん","ドレインパンチ","まもる"],["focussash","toxicorb","choiceband"],["trick","sweeper"],3.3,49.5,-0.4],
    ["milotic","ミロカロス","Milotic","water",null,95,60,79,100,125,81,3,["marvelscale","competitive"],["なみのり","れいとうビーム","じこさいせい","まもる"],["leftovers","sitrusberry","assaultvest"],["wall"],3.1,49.3,-0.2],
    ["rotomwash","ロトム（ウォッシュ）","Rotom-Wash","electric","water",50,65,107,105,107,86,4,["levitate"],["ハイドロポンプ","10まんボルト","ボルトチェンジ","でんじは"],["leftovers","choicescarf","sitrusberry"],["pivot","wall"],6.5,51.6,0.3],
    ["rotomheat","ロトム（ヒート）","Rotom-Heat","electric","fire",50,65,107,105,107,86,4,["levitate"],["オーバーヒート","10まんボルト","ボルトチェンジ","まもる"],["leftovers","choicescarf","sitrusberry"],["pivot"],4.4,50.4,0.0],
    ["snorlax","カビゴン","Snorlax","normal",null,160,110,65,65,110,30,1,["thickfat","gluttony"],["はらだいこ","しんそく","じしん","はたきおとす"],["sitrusberry","leftovers","choiceband"],["wall","setup"],3.5,49.8,-0.1],
    ["blissey","ハピナス","Blissey","normal",null,255,10,10,75,135,55,2,["naturalcure","healer"],["ちきゅうなげ","どくどく","タマゴうみ","まもる"],["heavydutyboots","leftovers"],["wall"],2.8,49.1,-0.3],
    ["skarmory","エアームド","Skarmory","steel","flying",65,80,140,40,70,70,2,["sturdy","weakarmor"],["ステルスロック","はねやすめ","ボディプレス","はたきおとす"],["leftovers","rockyhelmet","heavydutyboots"],["wall"],3.0,49.7,-0.2],
    ["magnezone","ジバコイル","Magnezone","electric","steel",70,70,115,130,90,60,4,["magnetpull","sturdy"],["10まんボルト","ラスターカノン","ボルトチェンジ","みがわり"],["choicespecs","airballoon","leftovers"],["trick"],2.6,49.0,-0.4],
    ["goodrahisui","ヒスイヌメルゴン","Goodra-Hisui","steel","dragon",80,100,100,110,150,60,8,["shellarmor","gooey"],["りゅうせいぐん","ラスターカノン","じこさいせい","どくどく"],["assaultvest","leftovers","rockyhelmet"],["wall"],3.2,49.9,0.1],
    ["arcanine","ウインディ","Arcanine","fire",null,90,110,80,100,80,95,1,["intimidate","flashfire"],["フレアドライブ","しんそく","おにび","まもる"],["sitrusberry","assaultvest","heavydutyboots"],["support","tank"],4.9,50.6,0.2],
    ["lapras","ラプラス","Lapras","water","ice",130,85,80,85,95,60,1,["waterabsorb","shellarmor"],["ふぶき","ハイドロポンプ","オーロラベール","まもる"],["lightclay","assaultvest","sitrusberry"],["support","wall"],3.4,49.6,0.0],
    ["glaceon","グレイシア","Glaceon","ice",null,65,60,110,130,95,65,4,["snowcloak","icebody"],["ふぶき","れいとうビーム","まもる","シャドーボール"],["choicespecs","lifeorb","sitrusberry"],["sweeper"],2.2,48.8,-0.2],
    ["sylveon","ニンフィア","Sylveon","fairy",null,95,65,65,110,130,60,6,["pixilate","cutecharm"],["ハイパーボイス","マジカルシャイン","まもる","でんじは"],["choicespecs","sitrusberry","leftovers"],["support","sweeper"],3.6,50.0,0.1],
    ["umbreon","ブラッキー","Umbreon","dark",null,95,65,110,60,130,65,2,["synchronize","innerfocus"],["どくどく","じこさいせい","はたきおとす","あくび"],["leftovers","heavydutyboots"],["wall"],2.4,49.2,-0.1],
    ["espeon","エーフィ","Espeon","psychic",null,65,65,60,130,95,110,2,["magicbounce","synchronize"],["サイコキネシス","マジカルシャイン","シャドーボール","みがわり"],["lifeorb","choicespecs","focussash"],["speed","pivot"],2.1,48.9,-0.3],
    ["hydreigon","サザンドラ","Hydreigon","dark","dragon",92,105,90,125,90,98,5,["levitate"],["あくのはどう","りゅうせいぐん","だいもんじ","まもる"],["choicespecs","lifeorb","choicescarf"],["sweeper"],4.1,50.3,0.2],
    ["conkeldurr","ローブシン","Conkeldurr","fighting",null,105,140,95,55,65,45,5,["guts","ironfist"],["ドレインパンチ","ばくれつパンチ","はたきおとす","まもる"],["flameorb","assaultvest","sitrusberry"],["tank"],2.9,49.4,-0.2],
    ["porygon2","ポリゴン2","Porygon2","normal",null,85,80,90,105,95,60,2,["traceability","download"],["トライアタック","れいとうビーム","じこさいせい","トリックルーム"],["eviolite","leftovers","sitrusberry"],["wall","support"],5.8,51.5,0.4],
    ["indeedeef","イエッサン♀","Indeedee-F","psychic","normal",70,55,65,95,105,85,8,["psychicsurge","healer"],["フォローミー","ワイドフォース","まもる","マジカルシャイン"],["sitrusberry","safetygoggles","covertcloak"],["support"],7.3,52.0,0.6],
    ["farigiraf","リキキリン","Farigiraf","normal","psychic",120,90,70,110,70,60,9,["armortail","sapsipper"],["ワイドフォース","トリックルーム","まもる","はたきおとす"],["leftovers","sitrusberry","assaultvest"],["support","wall"],5.2,50.8,0.3],
    ["torkoal","コータス","Torkoal","fire",null,70,85,140,85,70,20,3,["drought","shellarmor"],["ふんか","だいもんじ","あくび","まもる"],["charcoal","leftovers","sitrusberry"],["support"],4.7,50.5,0.1],
    ["pelipper","ペリッパー","Pelipper","water","flying",60,50,100,95,70,65,3,["drizzle","raindish"],["ぼうふう","なみのり","おいかぜ","まもる"],["focussash","leftovers","sitrusberry"],["support"],4.3,50.2,0.0],
    ["ninetalesalola","アローラキュウコン","Ninetales-Alola","ice","fairy",73,67,75,81,100,109,7,["snowwarning","snowcloak"],["ふぶき","ムーンフォース","オーロラベール","まもる"],["lightclay","focussash","sitrusberry"],["support","speed"],5.6,51.0,0.4],
    ["dracovish","ウオノラゴン","Dracovish","water","dragon",90,90,100,70,80,75,8,["strongjaw","waterabsorb"],["エラがみ","げきりん","じしん","まもる"],["choicescarf","choiceband","lifeorb"],["sweeper"],2.3,48.7,-0.5],
    ["regieleki","レジエレキ","Regieleki","electric",null,80,100,50,100,50,200,8,["transistor"],["ライジングボルト","10まんボルト","でんじは","まもる"],["lifeorb","focussash","choicespecs"],["speed"],3.1,49.5,-0.1],
    ["flygon","フライゴン","Flygon","ground","dragon",80,100,80,80,80,100,3,["levitate"],["じしん","げきりん","とんぼがえり","まもる"],["choicescarf","lifeorb","assaultvest"],["pivot"],2.0,48.6,-0.2],
    ["haxorus","オノノクス","Haxorus","dragon",null,76,147,90,60,70,97,5,["moldbreaker","rivalry"],["げきりん","じしん","つるぎのまい","ドラゴンクロー"],["lifeorb","choiceband","focussash"],["sweeper"],2.5,49.0,-0.3],
    ["pawmot","パーモット","Pawmot","electric","fighting",70,115,70,70,60,105,9,["ironfist","voltabsorb"],["ワイルドボルト","インファイト","ふくろだたき","まもる"],["focussash","choiceband","lifeorb"],["speed","support"],3.8,49.8,0.1],
    ["toedscruel","リククラゲ","Toedscruel","ground","grass",80,70,65,80,120,100,9,["mycelium","regenerator"],["キノコのほうし","だいちのちから","エナジーボール","まもる"],["rockyhelmet","leftovers","covertcloak"],["support","trick"],3.3,49.7,0.0],
    ["brutebonnet","アラブルタケ","Brute Bonnet","grass","dark",111,127,99,79,99,55,9,["protosynthesis"],["タネばくだん","はたきおとす","キノコのほうし","まもる"],["boosterenergy","assaultvest","sitrusberry"],["tank"],4.0,50.1,0.2],
    ["ironjugulis","テツノコウベ","Iron Jugulis","dark","flying",94,80,86,122,80,108,9,["quarkdrive"],["あくのはどう","ぼうふう","だいちのちから","まもる"],["boosterenergy","choicespecs","focussash"],["speed","sweeper"],3.6,49.9,0.1],
    ["ironmoth","テツノドクガ","Iron Moth","fire","poison",80,70,60,140,110,110,9,["quarkdrive"],["だいもんじ","ヘドロばくだん","エナジーボール","まもる"],["boosterenergy","choicespecs","lifeorb"],["speed","sweeper"],5.9,51.2,0.5],
    ["greattusk","イダイナキバ","Great Tusk","ground","fighting",115,131,131,53,53,87,9,["protosynthesis"],["じしん","インファイト","ステルスロック","はたきおとす"],["boosterenergy","leftovers","assaultvest"],["tank","pivot"],8.1,52.6,0.7],
    ["scizorlike","ハラバリー","Bellibolt","electric",null,109,64,91,103,83,45,9,["electromorphosis","staticc"],["10まんボルト","ヘドロウェーブ","まもる","でんじは"],["leftovers","assaultvest","sitrusberry"],["wall"],2.7,49.3,0.0],
    ["arceus","アルセウス","Arceus","normal",null,120,120,120,120,120,120,4,["multitype"],["さばきのつぶて","しんそく","つるぎのまい","まもる"],["silkscarf","leftovers","lifeorb"],["sweeper","setup"],3.2,51.8,0.2],
    ["suicune","スイクン","Suicune","water",null,100,75,115,90,115,85,2,["pressure","innerfocus"],["ねっとう","れいとうビーム","じこさいせい","まもる"],["leftovers","sitrusberry","assaultvest"],["wall"],2.6,49.4,-0.1],
    ["raikou","ライコウ","Raikou","electric",null,90,85,75,115,100,115,2,["pressure","innerfocus"],["10まんボルト","だいちのちから","でんじは","まもる"],["choicespecs","leftovers","lifeorb"],["speed"],2.4,49.1,-0.2],
    ["entei","エンテイ","Entei","fire",null,115,115,85,90,75,100,2,["pressure","innerfocus"],["せいなるほのお","しんそく","いわなだれ","まもる"],["assaultvest","choiceband","sitrusberry"],["tank"],2.2,48.9,-0.1],
    ["latios","ラティオス","Latios","dragon","psychic",80,90,80,130,110,110,3,["levitate"],["りゅうせいぐん","サイコキネシス","まもる","めいそう"],["lifeorb","choicespecs","softsand"],["sweeper"],2.9,49.6,0.0],
    ["latias","ラティアス","Latias","dragon","psychic",80,80,90,110,130,110,3,["levitate"],["りゅうせいぐん","サイコキネシス","じこさいせい","まもる"],["leftovers","lifeorb","sitrusberry"],["wall","support"],2.7,49.5,0.1],
    ["kyurem","キュレム","Kyurem","dragon","ice",125,130,90,130,90,95,5,["pressure"],["こおりのつぶて","りゅうせいぐん","ふぶき","まもる"],["choicespecs","leftovers","lifeorb"],["tank","sweeper"],4.5,50.7,0.3],
    ["eternatus","ムゲンダイナ","Eternatus","poison","dragon",140,85,95,145,95,130,8,["pressure"],["ダイマックスほう","ヘドロばくだん","かえんほうしゃ","まもる"],["leftovers","choicespecs","lifeorb"],["sweeper","wall"],5.1,52.3,0.4],
    ["zamazenta","ザマゼンタ","Zamazenta","fighting",null,92,130,115,80,115,138,8,["dauntlessshield"],["ボディプレス","きょじゅうだん","まもる","つるぎのまい"],["rustedshield","leftovers","assaultvest"],["wall","tank"],6.4,53.9,0.5],
    ["solgaleo","ソルガレオ","Solgaleo","psychic","steel",137,137,107,113,89,97,7,["fullmetalbody"],["メテオドライブ","インファイト","まもる","つるぎのまい"],["leftovers","clearamulet","lifeorb"],["tank"],3.4,50.6,0.1],
    ["lunala","ルナアーラ","Lunala","psychic","ghost",137,113,89,137,107,97,7,["shadowshield"],["シャドーレイ","サイコキネシス","まもる","めいそう"],["leftovers","lifeorb","focussash"],["tank","sweeper"],3.9,51.4,0.2],
    ["zekrom","ゼクロム","Zekrom","dragon","electric",100,150,120,120,100,90,5,["teravolt"],["クロスサンダー","げきりん","まもる","りゅうのまい"],["lifeorb","choiceband","leftovers"],["sweeper"],3.0,50.2,0.0],
    ["reshiram","レシラム","Reshiram","dragon","fire",100,120,100,150,120,90,5,["turboblaze"],["クロスフレイム","りゅうせいぐん","まもる","かえんほうしゃ"],["choicespecs","lifeorb","leftovers"],["sweeper"],2.8,50.0,-0.1],
  ];

  /* 展開 */
  const DEX = RAW.map((r) => ({
    id: r[0], ja: r[1], en: r[2],
    types: r[4] ? [r[3], r[4]] : [r[3]],
    base: { hp: r[5], atk: r[6], def: r[7], spa: r[8], spd: r[9], spe: r[10] },
    bst: r[5] + r[6] + r[7] + r[8] + r[9] + r[10],
    gen: r[11], abilities: r[12], moves: r[13], items: r[14], roles: r[15],
    usage: r[16], win: r[17], trend: r[18],
  }));
  /* ══════════ ⑫ 図鑑番号（本物の絵を出すため）══════════
     ★ 攻略サイトのように<b>本物のポケモンの絵</b>を出すための番号。
       絵は PokeAPI の公式アートを使い、一度見たものは Service Worker が控えるので
       <b>2回目からはオフラインでも出る</b>。取れないときは頭文字の丸に戻る。
     ★ form は<b>フォルム専用の番号</b>。見つからなければ dex の絵へ落ちる。 */
  const DEXNO = {
    garchomp: 445, dragonite: 149, mimikyu: 778, gholdengo: 1000, fluttermane: 987,
    ironvaliant: 1006, roaringmoon: 1005, ironhands: 992, kingambit: 983, chienpao: 1002,
    tinglu: 1003, chiyu: 1004, dragapult: 887, urshifusingle: 892, urshifurapid: 892,
    incineroar: 727, rillaboom: 812, amoonguss: 591, landorust: 645, tornadust: 641,
    toxapex: 748, corviknight: 823, ferrothorn: 598, heatran: 485, zapdos: 145,
    tapukoko: 785, tapufini: 788, tapulele: 786, tapubulu: 787, kartana: 798,
    celesteela: 797, glimmora: 970, palafin: 964, meowscarada: 908, skeledirge: 911,
    quaquaval: 914, baxcalibur: 998, ursalunabm: 901, annihilape: 979, garganacl: 934,
    dondozo: 977, clodsire: 980, ironbundle: 991, archaludon: 1018, ogerpon: 1017,
    calyrexshadow: 898, calyrexice: 898, zacian: 888, miraidon: 1008, koraidon: 1007,
    kyogre: 382, groudon: 383, rayquaza: 384, lugia: 249, hooh: 250,
    mewtwo: 150, giratina: 487, dialga: 483, palkia: 484, xerneas: 716,
    yveltal: 717, necrozmadm: 800, tyranitar: 248, metagross: 376, salamence: 373,
    gyarados: 130, charizard: 6, gengar: 94, gardevoir: 282, lucario: 448,
    togekiss: 468, azumarill: 184, whimsicott: 547, cresselia: 488, excadrill: 530,
    volcarona: 637, scizor: 212, breloom: 286, milotic: 350, rotomwash: 479,
    rotomheat: 479, snorlax: 143, blissey: 242, skarmory: 227, magnezone: 462,
    goodrahisui: 706, arcanine: 59, lapras: 131, glaceon: 471, sylveon: 700,
    umbreon: 197, espeon: 196, hydreigon: 635, conkeldurr: 534, porygon2: 233,
    indeedeef: 876, farigiraf: 981, torkoal: 324, pelipper: 279, ninetalesalola: 38,
    dracovish: 882, regieleki: 894, flygon: 330, haxorus: 612, pawmot: 921,
    toedscruel: 949, brutebonnet: 946, ironjugulis: 993, ironmoth: 994, greattusk: 984,
    scizorlike: 939, arceus: 493, suicune: 245, raikou: 243, entei: 244,
    latios: 381, latias: 380, kyurem: 646, eternatus: 890, zamazenta: 889,
    solgaleo: 791, lunala: 792, zekrom: 644, reshiram: 643,
  };
  const FORMNO = {
    ninetalesalola: 10100, rotomwash: 10008, rotomheat: 10006, landorust: 10068,
    tornadust: 10067, urshifurapid: 10191, calyrexshadow: 10194, calyrexice: 10193,
    ursalunabm: 10272, goodrahisui: 10244, palafin: 10258, indeedeef: 10101,
  };
  DEX.forEach((p) => { p.dex = DEXNO[p.id] || 0; p.form = FORMNO[p.id] || 0; });

  /* ══════════ ⑬ メガシンカ・ゲンシカイキ（★★ 2026-09-10 ご指定）══════════
     ★ <b>公式のものだけ</b>を入れてあります。
       （PokeAPI には非公式の「〜-mega」も混じっていますが、それは入れていません）
     ★ 数字（タイプ・種族値・特性）は PokeAPI から取った<b>本物</b>です。
     ★ ここに<b>タイプが変わる子</b>が多いのが大事なところ。たとえば
         ギャラドス … みず／ひこう（でんき4倍）→ <b>みず／あく（でんき無効）</b>
         リザードン … ほのお／ひこう（いわ4倍）→ X は <b>ほのお／ドラゴン</b>
       ので、メガを考えずに相性を出すと<b>読みが丸ごとひっくり返ります</b>。
     ★ 1チームに<b>1体だけ</b>。その決まりは mc-core.js の setMega が守ります。
     形： [ 日本語名, English, タイプ1, タイプ2, HP, こうげき, ぼうぎょ, とくこう, とくぼう, すばやさ, 特性, フォルム番号 ] */
  const MEGA_RAW = {
    charizard: [
      ["メガリザードンX", "Mega Charizard X", "fire", "dragon", 78, 130, 111, 130, 85, 100, "toughclaws", 10034],
      ["メガリザードンY", "Mega Charizard Y", "fire", "flying", 78, 104, 78, 159, 115, 100, "drought", 10035],
    ],
    gengar:     [["メガゲンガー", "Mega Gengar", "ghost", "poison", 60, 65, 80, 170, 95, 130, "shadowtag", 10038]],
    gyarados:   [["メガギャラドス", "Mega Gyarados", "water", "dark", 95, 155, 109, 70, 130, 81, "moldbreaker", 10041]],
    mewtwo: [
      ["メガミュウツーX", "Mega Mewtwo X", "psychic", "fighting", 106, 190, 100, 154, 100, 130, "steadfast", 10043],
      ["メガミュウツーY", "Mega Mewtwo Y", "psychic", null, 106, 150, 70, 194, 120, 140, "insomnia", 10044],
    ],
    scizor:     [["メガハッサム", "Mega Scizor", "bug", "steel", 70, 150, 140, 65, 100, 75, "technician", 10046]],
    tyranitar:  [["メガバンギラス", "Mega Tyranitar", "rock", "dark", 100, 164, 150, 95, 120, 71, "sandstream", 10049]],
    gardevoir:  [["メガサーナイト", "Mega Gardevoir", "psychic", "fairy", 68, 85, 65, 165, 135, 100, "pixilate", 10051]],
    metagross:  [["メガメタグロス", "Mega Metagross", "steel", "psychic", 80, 145, 150, 105, 110, 110, "toughclaws", 10076]],
    latias:     [["メガラティアス", "Mega Latias", "dragon", "psychic", 80, 100, 120, 140, 150, 110, "levitate", 10062]],
    latios:     [["メガラティオス", "Mega Latios", "dragon", "psychic", 80, 130, 100, 160, 120, 110, "levitate", 10063]],
    kyogre:     [["ゲンシカイオーガ", "Primal Kyogre", "water", null, 100, 150, 90, 180, 160, 90, "primordialsea", 10077]],
    groudon:    [["ゲンシグラードン", "Primal Groudon", "ground", "fire", 100, 180, 160, 150, 90, 90, "desolateland", 10078]],
    rayquaza:   [["メガレックウザ", "Mega Rayquaza", "dragon", "flying", 105, 180, 100, 180, 100, 115, "deltastream", 10079]],
    salamence:  [["メガボーマンダ", "Mega Salamence", "dragon", "flying", 95, 145, 130, 120, 90, 120, "aerilate", 10089]],
    garchomp:   [["メガガブリアス", "Mega Garchomp", "dragon", "ground", 108, 170, 115, 120, 95, 92, "sandforce", 10058]],
    lucario:    [["メガルカリオ", "Mega Lucario", "fighting", "steel", 70, 145, 88, 140, 70, 112, "adaptability", 10059]],
  };
  /* ★ ここではまだ BY_ID が作られていないので、DEX から直に引く。 */
  const _byId = {};
  DEX.forEach((p) => { _byId[p.id] = p; });
  Object.keys(MEGA_RAW).forEach((id) => {
    const p = _byId[id];
    if (!p) return;                       /* 図鑑にいない子のぶんは無視（データを増やさない） */
    p.megas = MEGA_RAW[id].map((r) => {
      const base = { hp: r[4], atk: r[5], def: r[6], spa: r[7], spd: r[8], spe: r[9] };
      return {
        ja: r[0], en: r[1], types: r[3] ? [r[2], r[3]] : [r[2]],
        base: base, bst: r[4] + r[5] + r[6] + r[7] + r[8] + r[9],
        abil: r[10], form: r[11],
      };
    });
  });
  const BY_ID = {};
  DEX.forEach((p) => { BY_ID[p.id] = p; });

  /* ══════════ ⑧ 人気の編成（サンプル） ══════════ */
  const TEAMS = [
    { id: "t1", ja: "パオジアン軸バランス", en: "Chien-Pao Balance",
      ids: ["chienpao", "gholdengo", "landorust", "amoonguss", "ironhands", "fluttermane"],
      usage: 6.4, win: 55.2,
      strong: { ja: "先手を取りやすく、どの並びにも同じ動きで入れる", en: "Fast and consistent into most leads" },
      weak:   { ja: "はがね・フェアリーの並びに火力が通りにくい", en: "Struggles into Steel + Fairy cores" } },
    { id: "t2", ja: "トリックルーム", en: "Trick Room",
      ids: ["calyrexice", "farigiraf", "ironhands", "amoonguss", "incineroar", "ursalunabm"],
      usage: 5.8, win: 54.1,
      strong: { ja: "速い相手を上から叩ける・受けが厚い", en: "Flips speed; very bulky" },
      weak:   { ja: "トリックルームを止められると一気に苦しい", en: "Falls apart if Trick Room is blocked" } },
    { id: "t3", ja: "晴れアタッカー", en: "Sun Offense",
      ids: ["torkoal", "ironmoth", "greattusk", "rillaboom", "gholdengo", "fluttermane"],
      usage: 4.9, win: 53.0,
      strong: { ja: "ほのお技の圧力がとにかく高い", en: "Overwhelming Fire pressure" },
      weak:   { ja: "天候を上書きされると火力が落ちる", en: "Weather war losses hurt a lot" } },
    { id: "t4", ja: "雨パーティ", en: "Rain",
      ids: ["pelipper", "urshifurapid", "kyogre", "rillaboom", "incineroar", "tornadust"],
      usage: 4.2, win: 52.6,
      strong: { ja: "みず技が全体に重く、速度も上がる", en: "Boosted Water damage and Speed" },
      weak:   { ja: "でんき・くさに弱く、天候を取られると崩れる", en: "Weak to Electric/Grass; weather reliant" } },
    { id: "t5", ja: "ドドゲザン＋いかく", en: "Kingambit + Intimidate",
      ids: ["kingambit", "incineroar", "landorust", "amoonguss", "rillaboom", "fluttermane"],
      usage: 5.5, win: 54.8,
      strong: { ja: "まけんきで いかく を逆手に取れる", en: "Turns Intimidate into a boost" },
      weak:   { ja: "かくとうタイプの一貫が刺さる", en: "Fighting types run through it" } },
    { id: "t6", ja: "ハバタクカミ軸", en: "Flutter Mane Core",
      ids: ["fluttermane", "ironhands", "landorust", "amoonguss", "incineroar", "urshifurapid"],
      usage: 7.1, win: 56.0,
      strong: { ja: "先制でゴースト・フェアリーの一貫を作れる", en: "Fast Ghost/Fairy pressure" },
      weak:   { ja: "耐久が低く、先制技で落とされやすい", en: "Frail; dies to priority" } },
    { id: "t7", ja: "スタンダード対面", en: "Standard Balance",
      ids: ["dragonite", "gholdengo", "greattusk", "amoonguss", "incineroar", "ironbundle"],
      usage: 6.0, win: 54.3,
      strong: { ja: "どんな相手にも噛み合う選出の幅", en: "Flexible into anything" },
      weak:   { ja: "決め手に欠け、長い試合になりやすい", en: "Lacks a clear win condition" } },
    { id: "t8", ja: "オーガポン＋雨受け", en: "Ogerpon Bulky",
      ids: ["ogerpon", "archaludon", "dondozo", "gholdengo", "incineroar", "tornadust"],
      usage: 3.8, win: 52.2,
      strong: { ja: "受けきってから展開できる", en: "Stalls, then sets up" },
      weak:   { ja: "特殊高火力に押し切られる", en: "Loses to heavy special attackers" } },
  ];

  /* ══════════ ⑨ 公開 ══════════ */
  window.MC_DATA = {
    TYPES, TK, CHART, ROLES, ABIL, MOVES, ITEMS, DEX, BY_ID, TEAMS,
    /* meta.json で上書きできる項目（使用率・勝率・トレンド・編成） */
    META_FIELDS: ["usage", "win", "trend"],
    VERSION: "2026-09-08",
  };
})();
